<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Feature 4 (3) - Offer Product</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5b02bb7f-fd6d-4f94-b298-4e98f115786d</testSuiteGuid>
   <testCaseLink>
      <guid>da3e0908-07aa-42ce-b3d0-e9b79f2d8d69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Offer Product/OFP001 - Offer Product without Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e0438190-d960-4c3c-8dc2-f6afe5ad850b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7bca9ff5-b254-4204-919f-37f4a30968cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Offer Product/OFP002 - Offer Product with Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3d44b17-b6e4-4e38-8bed-b9c67085a1ac</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f8707ee0-a49b-4dd0-8f7c-793bfff13618</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Offer Product/OFP003 - Repeated Offer Product with Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0afb88ac-cf00-4762-bb25-6c677d577489</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ddb29185-2147-44b5-af47-229d30defeda</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Offer Product/OFP004 - Repeated Offer Product without Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d95792dd-0c68-415a-87a7-1899d4533c1d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8eecf927-8e19-4f89-95f7-404c8c457ad1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Offer Product/OFP005 - High Bid Offer Product without Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45daad47-fe9e-4415-b06d-8864a8fce003</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7b0e7ce7-2638-4495-aa1d-a831ba540817</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Offer Product/OFP006 - High Bid Offer Product with Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b6814ed-8e8b-4ed2-8228-6a2b458bb506</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>59edc8e0-e10c-4caa-a419-93d11677b650</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Offer Product/OFP007 - Low Bid Offer Product without Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cfec8397-2011-48e0-8f42-08480726ad95</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c4cb517-478b-4cef-b7a1-a04144f91126</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Offer Product/OFP008 - Low Bid Offer Product witht Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d59a0de-4174-498a-818e-73de529aee88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d799c35b-0b09-4c9e-a942-5837672e6395</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Step Definition/Feature Offer Product/OFP009 - Offer Product with Login Not Complete Profile</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23252ad1-6b57-4bb9-a665-240127228380</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
